author: 若离QQ：2909998156
# 调试模式，用于寻找错误出现的坐标，默认为false
# 特别提示：调试完成后请记得将debug改为false
# 特别提示：调试完成后请记得将debug改为false
# 特别提示：调试完成后请记得将debug改为false
debug: false
# 推送方式：0：邮件推送；1：qmsg推送；2：pushplus推送
sendType: 0
# 当且仅当sendType为0时有用，邮箱API的地址
emailApiUrl: 'https://api.ruoli.cc/sendMail'
# 当且仅当sendType为1时有用，qmsg的Key（如需使用请自行更改）
myQmsgKey: ''



#用户组配置
##################################################
# 温馨提示：请仔细注意每个模板是属于哪个任务类型的配置！##
##################################################
users:
  # 第三个用户配置
  # 以下配置为签到
  # 这里默认仅适配武汉船舶职业技术学院，其他学校自行修改
  - user:
      # 任务类型（收集：0、签到：1、查寝：2）
      type: 1
      #username 学号或者工号
      username: '2054102037'
      #password 密码
      password: 'wcl171972148'
      #address 地址，定位信息
      address: '中国福建省福州市长乐区'
      #sendKey 当sendType为0时代表邮箱，当sendType为1时代表接收消息的QQ号码 当sendType为2时代表接收消息的pushplus token
      sendKey: '171972148@qq.com'
      #school 学校全称
      schoolName: 福州外语外贸学院
      # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
      #lon 经度
      lon: 119.506747
      #lat 纬度
      lat: 25.926478
      #abnormalReason 反馈信息（这个一般不用配置，但是不能删除，删除会报错）
      abnormalReason: ''
      #photo 签到照片，不需要可不填，或者直接删除
      photo: sign.jpg
      # 是否检查表单的标题（1代表检查，0代表不检查）
      checkTitle: 0
      #代理ip信息（格式为：网络协议://ip地址:端口   如：http://127.0.0.1:7890）
      proxy:
      # 表单信息
      forms:
        - form:
            title: 早上的身体健康情况
            value: 健康
        - form:
            title: 早上的体温是多少
            value: 正常（36.0℃-37.2℃）

  - user:
      # 任务类型（收集：0、签到：1、查寝：2）
      type: 1
      #username 学号或者工号
      username: '2054102047'
      #password 密码
      password: 'zwf976842659'
      #address 地址，定位信息
      address: '中国福建省福州市长乐区'
      #sendKey 当sendType为0时代表邮箱，当sendType为1时代表接收消息的QQ号码
      sendKey: '958425861@qq.com'
      #school 学校全称
      schoolName: 福州外语外贸学院
      # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
      #lon 经度
      lon: 119.506747
      #lat 纬度
      lat: 25.926478
      #abnormalReason 反馈信息（这个一般不用配置，但是不能删除，删除会报错）
      abnormalReason: ''
      #photo 签到照片，不需要可不填，或者直接删除
      photo: sign.jpg
      # 是否检查表单的标题（1代表检查，0代表不检查）
      checkTitle: 0
      #代理ip信息（格式为：网络协议://ip地址:端口   如：http://127.0.0.1:7890）
      proxy:
      # 表单信息
      forms:
        - form:
            title: 早上的身体健康情况
            value: 健康
        - form:
            title: 早上的体温是多少
            value: 正常（36.0℃-37.2℃）

  - user:
      # 任务类型（收集：0、签到：1、查寝：2）
      type: 1
      #username 学号或者工号
      username: '1931201209'
      #password 密码
      password: 'hsyhsy0222'
      #address 地址，定位信息
      address: '中国福建省福州市长乐区'
      #sendKey 当sendType为0时代表邮箱，当sendType为1时代表接收消息的QQ号码
      sendKey: '2571601035@qq.com'
      #school 学校全称
      schoolName: 福州外语外贸学院
      # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
      #lon 经度
      lon: 119.506747
      #lat 纬度
      lat: 25.926478
      #abnormalReason 反馈信息（这个一般不用配置，但是不能删除，删除会报错）
      abnormalReason: ''
      #photo 签到照片，不需要可不填，或者直接删除
      photo: sign.jpg
      # 是否检查表单的标题（1代表检查，0代表不检查）
      checkTitle: 0
      #代理ip信息（格式为：网络协议://ip地址:端口   如：http://127.0.0.1:7890）
      proxy:
      # 表单信息
      forms:
        - form:
            title: 早上的身体健康情况
            value: 健康
        - form:
            title: 早上的体温是多少
            value: 正常（36.0℃-37.2℃）

  - user:
      # 任务类型（收集：0、签到：1、查寝：2）
      type: 1
      #username 学号或者工号
      username: '1935504215'
      #password 密码
      password: '123456789+hxm'
      #address 地址，定位信息
      address: '中国福建省福州市长乐区'
      #sendKey 当sendType为0时代表邮箱，当sendType为1时代表接收消息的QQ号码
      sendKey: '1846814746@qq.com'
      #school 学校全称
      schoolName: 福州外语外贸学院
      # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
      #lon 经度
      lon: 119.506747
      #lat 纬度
      lat: 25.926478
      #abnormalReason 反馈信息（这个一般不用配置，但是不能删除，删除会报错）
      abnormalReason: ''
      #photo 签到照片，不需要可不填，或者直接删除
      photo: sign.jpg
      # 是否检查表单的标题（1代表检查，0代表不检查）
      checkTitle: 0
      #代理ip信息（格式为：网络协议://ip地址:端口   如：http://127.0.0.1:7890）
      proxy:
      # 表单信息
      forms:
        - form:
            title: 早上的身体健康情况
            value: 健康
        - form:
            title: 早上的体温是多少
            value: 正常（36.0℃-37.2℃）

  - user:
      # 任务类型（收集：0、签到：1、查寝：2）
      type: 1
      #username 学号或者工号
      username: '2054102029'
      #password 密码
      password: 'ldn160160'
      #address 地址，定位信息
      address: '中国福建省福州市长乐区'
      #sendKey 当sendType为0时代表邮箱，当sendType为1时代表接收消息的QQ号码
      sendKey: '97921100@qq.com'
      #school 学校全称
      schoolName: 福州外语外贸学院
      # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
      #lon 经度
      lon: 119.506747
      #lat 纬度
      lat: 25.926478
      #abnormalReason 反馈信息（这个一般不用配置，但是不能删除，删除会报错）
      abnormalReason: ''
      #photo 签到照片，不需要可不填，或者直接删除
      photo: sign.jpg
      # 是否检查表单的标题（1代表检查，0代表不检查）
      checkTitle: 0
      #代理ip信息（格式为：网络协议://ip地址:端口   如：http://127.0.0.1:7890）
      proxy:
      # 表单信息
      forms:
        - form:
            title: 早上的身体健康情况
            value: 健康
        - form:
            title: 早上的体温是多少
            value: 正常（36.0℃-37.2℃）

  - user:
      # 任务类型（收集：0、签到：1、查寝：2）
      type: 1
      #username 学号或者工号
      username: '2054102017'
      #password 密码
      password: 'hyb,492,2'
      #address 地址，定位信息
      address: '中国福建省福州市长乐区'
      #sendKey 当sendType为0时代表邮箱，当sendType为1时代表接收消息的QQ号码
      sendKey: '870310025@qq.com'
      #school 学校全称
      schoolName: 福州外语外贸学院
      # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
      #lon 经度
      lon: 119.506747
      #lat 纬度
      lat: 25.926478
      #abnormalReason 反馈信息（这个一般不用配置，但是不能删除，删除会报错）
      abnormalReason: ''
      #photo 签到照片，不需要可不填，或者直接删除
      photo: sign.jpg
      # 是否检查表单的标题（1代表检查，0代表不检查）
      checkTitle: 0
      #代理ip信息（格式为：网络协议://ip地址:端口   如：http://127.0.0.1:7890）
      proxy:
      # 表单信息
      forms:
        - form:
            title: 早上的身体健康情况
            value: 健康
        - form:
            title: 早上的体温是多少
            value: 正常（36.0℃-37.2℃）

  - user:
      # 任务类型（收集：0、签到：1、查寝：2）
      type: 1
      #username 学号或者工号
      username: '2054102001'
      #password 密码
      password: 'baoweixu1019'
      #address 地址，定位信息
      address: '中国福建省福州市长乐区'
      #sendKey 当sendType为0时代表邮箱，当sendType为1时代表接收消息的QQ号码
      sendKey: '1421341884@qq.com'
      #school 学校全称
      schoolName: 福州外语外贸学院
      # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
      #lon 经度
      lon: 119.506747
      #lat 纬度
      lat: 25.926478
      #abnormalReason 反馈信息（这个一般不用配置，但是不能删除，删除会报错）
      abnormalReason: ''
      #photo 签到照片，不需要可不填，或者直接删除
      photo: sign.jpg
      # 是否检查表单的标题（1代表检查，0代表不检查）
      checkTitle: 0
      #代理ip信息（格式为：网络协议://ip地址:端口   如：http://127.0.0.1:7890）
      proxy:
      # 表单信息
      forms:
        - form:
            title: 早上的身体健康情况
            value: 健康
        - form:
            title: 早上的体温是多少
            value: 正常（36.0℃-37.2℃）

  - user:
      # 任务类型（收集：0、签到：1、查寝：2）
      type: 1
      #username 学号或者工号
      username: '2034008042'
      #password 密码
      password: 'Yyx15860455098'
      #address 地址，定位信息
      address: '中国福建省福州市长乐区'
      #sendKey 当sendType为0时代表邮箱，当sendType为1时代表接收消息的QQ号码
      sendKey: '1429399063@qq.com'
      #school 学校全称
      schoolName: 福州外语外贸学院
      # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
      #lon 经度
      lon: 119.506747
      #lat 纬度
      lat: 25.926478
      #abnormalReason 反馈信息（这个一般不用配置，但是不能删除，删除会报错）
      abnormalReason: ''
      #photo 签到照片，不需要可不填，或者直接删除
      photo: sign.jpg
      # 是否检查表单的标题（1代表检查，0代表不检查）
      checkTitle: 0
      #代理ip信息（格式为：网络协议://ip地址:端口   如：http://127.0.0.1:7890）
      proxy:
      # 表单信息
      forms:
        - form:
            title: 早上的身体健康情况
            value: 健康
        - form:
            title: 早上的体温是多少
            value: 正常（36.0℃-37.2℃）
